name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: |
          echo "Building with path prefix..."
          npm run build -- --prefix-paths
        env:
          PREFIX_PATHS: "true"

      - name: Debug build output
        run: |
          echo "Checking build output..."
          ls -la public/

      - name: Prepare docs directory
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r public/* docs/
          cp -r static/* docs/
          touch docs/.nojekyll

      - name: Verify docs content
        run: |
          echo "Checking docs directory content..."
          ls -la docs/

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Deploy Gatsby site to docs folder" || echo "No changes to commit"
          git push
