name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: npm run build -- --prefix-paths
        env:
          PREFIX_PATHS: true

      - name: Prepare docs directory
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r public/* docs/
          touch docs/.nojekyll
          # cp public/404.html docs/404.html
          echo "Path prefix check in docs:"
          grep -r "/subsorter-web/" docs/ --include="*.html" || echo "Warning: Path prefix not found in HTML files"

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Deploy Gatsby site to docs folder" || echo "No changes to commit"
          git push
